export const icons = {
  approve: 'check_circle',
  checkin: 'lock',
  checkout: 'lock_open',
  copy: 'content_copy',
  delete: 'delete',
  download: 'file_download',
  edit: 'mode_edit',
  forceundocheckout: 'undo',
  move: 'folder',
  preview: 'search',
  publish: 'publish',
  setpermissions: 'report_problem',
  undocheckout: 'undo',
  versions: 'sd_storage',
}
