export const resources = {
    EMAIL_IS_NOT_VALID_MESSAGE: 'Please provide a valid e-mail address!',
    PASSWORD_IS_NOT_VALID_MESSAGE: 'Please provide a password!',
    WRONG_USERNAME_OR_PASSWORD: 'Wrong user name or password',
    EMAIL_INPUT_LABEL: 'E-mail',
    PASSWORD_INPUT_LABEL: 'Password',
    EMAIL_INPUT_PLACEHOLDER: 'E-mail',
    PASSWORD_INPUT_PLACEHOLDER: 'Password',
    LOGIN_BUTTON_TEXT: 'Login',
    LOGIN_TAB_TEXT: 'Login',
    REGISTER_TAB_TEXT: 'Register',
    WELCOME_MESSAGE: 'Welcome to the sensenet ECM Document Management System Experiment! We are thrilled to have you here. Please log in, or register!',
    REGISTRATION_BUTTON_TEXT: 'Register',
    EMAIL_INPUT_FORMAT_PLACEHOLDER: 'example@domain.com',
    CONFIRM_PASSWORD_INPUT_LABEL: 'Confirm password',
    PASSWORD_SHOULD_BE_VALID: 'Password needs to contain at least 3 characters!',
    PASSWORDS_SHOULD_MATCH: 'Passwords should match!',
    USER_IS_ALREADY_REGISTERED: 'The email address you have entered is already registered!',
    CAPTCHA_ERROR: 'Please complete the captcha!'
}