export const mockInstance = {
  clearDelayTimeouts: () => {},
  destroy: () => {},
  disable: () => {},
  enable: () => {},
  hide: () => {},
  hideWithInteractivity: (event: MouseEvent) => {},
  id: 1,
  plugins: [],
  popper: {} as any,
  popperInstance: null,
  props: {} as any,
  reference: {} as any,
  setContent: () => {},
  setProps: (porp) => ({}),
  show: () => {},
  state: {
    isEnabled: false,
    isVisible: false,
    isDestroyed: false,
    isMounted: false,
    isShown: false,
  },
  unmount: () => {},
}
