import { pathWithQueryParams } from '../../../src/services/query-string-builder'

describe('Permission editor group switcher and force relations', () => {
  beforeEach(() => {
    cy.login()
    cy.visit(pathWithQueryParams({ path: '/', newParams: { repoUrl: Cypress.env('repoUrl') } }))
  })

  it('switching a group switcher influences the permission items', () => {
    cy.get('[data-test="drawer-menu-item-content"]').click()
    cy.get('[data-test="menu-item-it-workspace"]').rightclick()
    cy.get('[data-test="content-context-menu-setpermissions"]').click()
    cy.get('[data-test="set-on-this-visitors"]').click()
    cy.get('[data-test="switcher-read"]').click()

    cy.get('[data-test="switcher-see"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-preview"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-previewwithoutwatermark"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-previewwithoutredaction"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-open"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')

    cy.get('[data-test="permission-editor-submit"]').click()
  })

  it('force relations should work properly', () => {
    cy.get('[data-test="drawer-menu-item-content"]').click()
    cy.get('[data-test="menu-item-it-workspace"]').rightclick()
    cy.get('[data-test="content-context-menu-setpermissions"]').click()
    cy.get('[data-test="set-on-this-visitors"]').click()

    //All permissions should be disabled on Read tab
    cy.get('[data-test="switcher-see"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-preview"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-previewwithoutwatermark"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-previewwithoutredaction"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')
    cy.get('[data-test="switcher-open"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(238, 238, 238)')

    cy.get('[data-test="switcher-open"]').click()

    //All permissions should be enabled on Read tab
    cy.get('[data-test="switcher-see"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(255, 255, 255)')
    cy.get('[data-test="switcher-preview"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(255, 255, 255)')
    cy.get('[data-test="switcher-previewwithoutwatermark"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(255, 255, 255)')
    cy.get('[data-test="switcher-previewwithoutredaction"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(255, 255, 255)')
    cy.get('[data-test="switcher-open"]')
      .parent()
      .find('.MuiSwitch-track')
      .should('have.css', 'background-color', 'rgb(255, 255, 255)')

    cy.get('[data-test="permission-editor-submit"]').click()
  })
})
