#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check if running in a terminal
if [[ "$OSTYPE" == "linux-gnu"* || "$OSTYPE" == "darwin"* ]]; then
    # Unix-like OS detected, proceed with redirection
    exec >/dev/tty 2>&1
fi

# Continue with the rest of the script
yarn lint-staged
