#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
if [[ "$OSTYPE" == "linux-gnu"* || "$OSTYPE" == "darwin"* ]] &&!("$PSVersionTable.PSVersion.Major" -ge 5); then
    # Unix-like OS detected, proceed with redirection
    exec >/dev/tty 2>&1
elif $PSVersionTable.PSVersion.Major -lt 5; then
    # PowerShell version less than 5, assume Unix-like environment
    exec >/dev/tty 2>&1
fi
yarn lint-staged
